export type SkillStatus = 'mastered' | 'learning' | 'planned'
export type SkillLink = [string, string]
export type Point = { x: number; y: number }

export interface SkillNode {
  id: string
  status: SkillStatus
  x: number
  y: number
  radius?: number
  amplitude?: number
  speed?: number
  phase?: number
  lineAmplitude?: number
  lineSpeed?: number
  linePhase?: number
}

export const skillLinks: SkillLink[] = [
  // 前端 / 开发
  ['vue', 'typescript'],
  ['vue', 'scss'],
  ['vue', 'vite'],
  ['typescript', 'vite'],
  ['typescript', 'node'],
  ['typescript', 'react'],
  ['node', 'agent-flow'],
  ['react', 'agent-flow'],
  ['webgl', 'modeling-3d'],

  // 创意 / 艺术
  ['photography', 'video-editing'],
  ['video-editing', 'modeling-3d'],
  ['piano', 'dance'],
  ['photography', 'modeling-3d'],

  // 运动 / 户外
  ['badminton', 'tennis'],
  ['swimming', 'surfing'],
  ['skiing', 'surfing'],
  ['tennis', 'skiing'],

  // 语言 / 生活 / 个人成长
  ['chinese', 'english'],
  ['english', 'japanese'],
  ['cooking', 'finance'],
  ['english', 'love'],
  ['japanese', 'love'],

  // 跨类连接
  ['vue', 'webgl'],
  ['agent-flow', 'finance'],
  ['video-editing', 'photography'],
  ['modeling-3d', 'webgl'],
  ['english', 'agent-flow'],
  ['cooking', 'love'],
]

export const mySkills: SkillNode[] = [
  // ===== 前端 / 开发（左上）=====
  {
    id: 'vue',
    status: 'mastered',
    x: -250,
    y: -170,
    radius: 30,
    amplitude: 4,
    speed: 0.001,
    phase: 0.3,
    lineAmplitude: 12,
    lineSpeed: 0.001,
    linePhase: 0.2,
  },
  {
    id: 'typescript',
    status: 'mastered',
    x: -150,
    y: -220,
    radius: 28,
    amplitude: 4,
    speed: 0.0011,
    phase: 1.2,
    lineAmplitude: 10,
    lineSpeed: 0.001,
    linePhase: 0.9,
  },
  {
    id: 'scss',
    status: 'mastered',
    x: -310,
    y: -70,
    radius: 26,
    amplitude: 3,
    speed: 0.001,
    phase: 2.1,
    lineAmplitude: 10,
    lineSpeed: 0.0011,
    linePhase: 1.4,
  },
  {
    id: 'vite',
    status: 'mastered',
    x: -180,
    y: -100,
    radius: 25,
    amplitude: 3,
    speed: 0.001,
    phase: 0.8,
    lineAmplitude: 8,
    lineSpeed: 0.0012,
    linePhase: 1.7,
  },
  {
    id: 'node',
    status: 'learning',
    x: -80,
    y: -160,
    radius: 27,
    amplitude: 4,
    speed: 0.00115,
    phase: 2.6,
    lineAmplitude: 11,
    lineSpeed: 0.0011,
    linePhase: 2.2,
  },
  {
    id: 'react',
    status: 'learning',
    x: -60,
    y: -260,
    radius: 27,
    amplitude: 4,
    speed: 0.0011,
    phase: 1.8,
    lineAmplitude: 12,
    lineSpeed: 0.001,
    linePhase: 2.5,
  },

  // ===== AI / 技术延伸（右上）=====
  {
    id: 'agent-flow',
    status: 'learning',
    x: 150,
    y: -220,
    radius: 28,
    amplitude: 4,
    speed: 0.00105,
    phase: 0.6,
    lineAmplitude: 12,
    lineSpeed: 0.001,
    linePhase: 0.4,
  },
  {
    id: 'webgl',
    status: 'planned',
    x: 260,
    y: -170,
    radius: 27,
    amplitude: 3,
    speed: 0.00095,
    phase: 1.1,
    lineAmplitude: 10,
    lineSpeed: 0.001,
    linePhase: 1.2,
  },

  // ===== 创意 / 艺术（右侧）=====
  {
    id: 'photography',
    status: 'learning',
    x: 320,
    y: -20,
    radius: 27,
    amplitude: 3,
    speed: 0.0011,
    phase: 2.4,
    lineAmplitude: 8,
    lineSpeed: 0.0011,
    linePhase: 1.9,
  },
  {
    id: 'video-editing',
    status: 'mastered',
    x: 260,
    y: 70,
    radius: 29,
    amplitude: 4,
    speed: 0.001,
    phase: 2.1,
    lineAmplitude: 11,
    lineSpeed: 0.001,
    linePhase: 2.3,
  },
  {
    id: 'modeling-3d',
    status: 'mastered',
    x: 170,
    y: 150,
    radius: 30,
    amplitude: 4,
    speed: 0.00105,
    phase: 0.9,
    lineAmplitude: 12,
    lineSpeed: 0.0012,
    linePhase: 1.6,
  },
  {
    id: 'piano',
    status: 'learning',
    x: 330,
    y: 150,
    radius: 26,
    amplitude: 3,
    speed: 0.001,
    phase: 1.7,
    lineAmplitude: 9,
    lineSpeed: 0.0011,
    linePhase: 2.8,
  },
  {
    id: 'dance',
    status: 'planned',
    x: 280,
    y: 230,
    radius: 26,
    amplitude: 3,
    speed: 0.001,
    phase: 2.9,
    lineAmplitude: 8,
    lineSpeed: 0.001,
    linePhase: 0.7,
  },

  // ===== 运动 / 户外（下方）=====
  {
    id: 'badminton',
    status: 'mastered',
    x: -150,
    y: 220,
    radius: 27,
    amplitude: 3,
    speed: 0.001,
    phase: 1.3,
    lineAmplitude: 9,
    lineSpeed: 0.001,
    linePhase: 1.1,
  },
  {
    id: 'tennis',
    status: 'learning',
    x: -40,
    y: 260,
    radius: 27,
    amplitude: 4,
    speed: 0.0011,
    phase: 2.2,
    lineAmplitude: 10,
    lineSpeed: 0.0011,
    linePhase: 2.4,
  },
  {
    id: 'skiing',
    status: 'learning',
    x: 70,
    y: 250,
    radius: 28,
    amplitude: 4,
    speed: 0.00105,
    phase: 0.5,
    lineAmplitude: 12,
    lineSpeed: 0.001,
    linePhase: 1.8,
  },
  {
    id: 'swimming',
    status: 'mastered',
    x: -250,
    y: 160,
    radius: 26,
    amplitude: 3,
    speed: 0.001,
    phase: 2.7,
    lineAmplitude: 8,
    lineSpeed: 0.0012,
    linePhase: 0.6,
  },
  {
    id: 'surfing',
    status: 'planned',
    x: 180,
    y: 290,
    radius: 26,
    amplitude: 3,
    speed: 0.00095,
    phase: 1.5,
    lineAmplitude: 9,
    lineSpeed: 0.001,
    linePhase: 1.4,
  },
  {
    id: 'racing',
    status: 'planned',
    x: 300,
    y: 320,
    radius: 25,
    amplitude: 3,
    speed: 0.001,
    phase: 2.5,
    lineAmplitude: 8,
    lineSpeed: 0.0011,
    linePhase: 2.1,
  },

  // ===== 语言 / 生活 / 个人成长（左侧偏下）=====
  {
    id: 'cooking',
    status: 'mastered',
    x: -330,
    y: 60,
    radius: 28,
    amplitude: 3,
    speed: 0.001,
    phase: 1.9,
    lineAmplitude: 8,
    lineSpeed: 0.001,
    linePhase: 2.6,
  },
  {
    id: 'finance',
    status: 'learning',
    x: -300,
    y: 180,
    radius: 27,
    amplitude: 3,
    speed: 0.001,
    phase: 0.4,
    lineAmplitude: 9,
    lineSpeed: 0.0011,
    linePhase: 1.5,
  },
  {
    id: 'chinese',
    status: 'mastered',
    x: -270,
    y: -10,
    radius: 28,
    amplitude: 3,
    speed: 0.001,
    phase: 2.3,
    lineAmplitude: 8,
    lineSpeed: 0.001,
    linePhase: 0.3,
  },
  {
    id: 'english',
    status: 'mastered',
    x: -190,
    y: 80,
    radius: 27,
    amplitude: 3,
    speed: 0.0011,
    phase: 1.6,
    lineAmplitude: 9,
    lineSpeed: 0.001,
    linePhase: 1.7,
  },
  {
    id: 'japanese',
    status: 'learning',
    x: -100,
    y: 120,
    radius: 27,
    amplitude: 4,
    speed: 0.00105,
    phase: 0.8,
    lineAmplitude: 10,
    lineSpeed: 0.0011,
    linePhase: 2.2,
  },
  {
    id: 'love',
    status: 'planned',
    x: -20,
    y: 170,
    radius: 26,
    amplitude: 3,
    speed: 0.001,
    phase: 2.8,
    lineAmplitude: 8,
    lineSpeed: 0.001,
    linePhase: 1.9,
  },
]

export const centerLabel = 'Jackie'
